<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE produits [
    <!ELEMENT produits (produit+)>
    <!ELEMENT produit (libelle,categorie,stock)>
    <!ELEMENT libelle (#PCDATA)>
    <!ELEMENT categorie (libelle)>
    <!ELEMENT stock (#PCDATA)>
    <!ATTLIST produit numProd ID #REQUIRED>
    <!ATTLIST categorie CID IDREF #REQUIRED>
]>
<produits>
    <produit numProd="a1999">
        <libelle></libelle>
        <categorie CID="a1999">
            <libelle></libelle>
        </categorie>
        <stock></stock>
    </produit>
</produits>